version: '3.8'

services:
  # MySQLデータベースサービス
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: my_ec_site_db
    ports:
      - "3307:3306" # ローカルからDBにアクセスしたい場合用（CIでは不要）
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p${DB_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Spring Bootアプリケーションサービス
  app:
    build:
      context: .
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy # dbサービスが起動してからappサービスを起動する
    environment:
      TZ: Asia/Tokyo
#      SPRING_PROFILES_ACTIVE: test  # 'test'プロファイルを有効にする
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      STRIPE_API_KEY: ${STRIPE_API_KEY}
      FRONTEND_BASE_URL: ${FRONTEND_BASE_URL}
      STRIPE_RETURN_URL: ${STRIPE_RETURN_URL}
      GMAIL_USERNAME: ${GMAIL_USERNAME}
      GMAIL_APP_PASSWORD: ${GMAIL_APP_PASSWORD}
    ports:
      - "8080:8080"