services:
  # MySQLデータベースサービス
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 1234 # テスト用の仮パスワード
      MYSQL_DATABASE: my_ec_site_db_test # テスト専用DB
    ports:
      - "3307:3306" # ローカルからDBにアクセスしたい場合用（CIでは不要）
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p1234" ]
      interval: 10s
      timeout: 5s
      retries: 5

  # Spring Bootアプリケーションサービス
  app:
    build:
      context: ./backend
      args:
        - APP_JWT_SECRET=${APP_JWT_SECRET}
        - STRIPE_API_KEY=${STRIPE_API_KEY}
    env_file:
      - ./.env
    depends_on:
      db:
        condition: service_healthy # dbサービスが起動してからappサービスを起動する
    environment:
      SPRING_PROFILES_ACTIVE: test
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/my_ec_site_db_test
      DB_USERNAME: root
      DB_PASSWORD: 1234
    # このコンテナで実行するコマンドを上書きし、テストを実行する
    command: ./mvnw test

#  frontend:
#    build: ./frontend # frontendディレクトリをビルド
#    ports:
#      - "3000:3000" # ローカルの3000番ポートをコンテナの3000番に接続
#    volumes:
#      - ./frontend:/app # ソースコードの変更を即時反映
#      - /app/node_modules # node_modulesはコンテナ内のものを維持