# ワークフローの名前 (GitHubのActionsタブに表示される)
name: Java CI with Maven

# ワークフローが実行されるきっかけ(トリガー)を設定
on:
  # mainブランチにpushされた時
  push:
    branches: [ "main", "develop" ]
  # mainブランチに対するPull Requestが作成・更新された時
  pull_request:
    branches: [ "main", "develop" ]

# 実行するジョブを定義
jobs:
  # 'build' という名前のジョブ
  build:
    # ジョブを実行する仮想環境OSを指定
    runs-on: ubuntu-latest

    # ジョブ内のステップ(手順)を定義
    steps:
      # --- セットアップ ---
      # ステップ1: リポジトリのソースコードをチェックアウトする
      - name: Checkout repository
        uses: actions/checkout@v4

        # --- Docker上でテストを実行 ---
      - name: Build and Test with Docker Compose
        run: docker compose up --build --exit-code-from app