# ワークフローの名前 (GitHubのActionsタブに表示される)
name: Java CI with Maven

# ワークフローが実行されるきっかけ(トリガー)を設定
on:
  # mainブランチにpushされた時
  push:
    branches: [ "develop" ]
  # mainブランチに対するPull Requestが作成・更新された時
  pull_request:
    branches: [ "develop" ]

# 実行するジョブを定義
jobs:
  # 'build' という名前のジョブ
  build:
    # ジョブを実行する仮想環境OSを指定
    runs-on: ubuntu-latest

    # ジョブ内のステップ(手順)を定義
    steps:
      # --- セットアップ ---
      # ステップ1: リポジトリのソースコードをチェックアウトする
      - name: Checkout repository
        uses: actions/checkout@v4

      # ステップ2: JDK 21のセットアップとMavenキャッシュの有効化
      - name: Set up JDK 21 and Cache Maven packages
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

        # --- Docker上でテストを実行 ---
      - name: Run tests with Docker Compose
        env:
          STRIPE_API_KEY: ${{ secrets.STRIPE_API_KEY }}
        run: docker compose -f docker-compose.ci.yml up --build --exit-code-from app