# ワークフローの名前 (GitHubのActionsタブに表示される)
name: Java CI with Maven

# ワークフローが実行されるきっかけ(トリガー)を設定
on:
  # mainブランチにpushされた時
  push:
    branches: [ "main" ]
  # mainブランチに対するPull Requestが作成・更新された時
  pull_request:
    branches: [ "main" ]

# 実行するジョブを定義
jobs:
  # 'build' という名前のジョブ (名前は任意)
  build:
    # ジョブを実行する仮想環境OSを指定 (Ubuntuの最新版)
    runs-on: ubuntu-latest

    # ジョブ内のステップ(手順)を定義
    steps:
      # --- セットアップ ---
      # ステップ1: リポジトリのソースコードをチェックアウトする
      - name: Checkout repository
        uses: actions/checkout@v4

      # ステップ2: Java (JDK) 環境をセットアップする
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      # ステップ3: Mavenの依存関係をキャッシュする (ビルド高速化のため)
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # --- ビルドとテスト ---
      # ステップ4: Mavenでビルドとテストを実行する
      - name: Build and test with Maven
        run: mvn -B package --file pom.xml